building: 'chgh'
elevators:
  - id: 0
    elevator_size:
      x: 1.6
      y: 1.6
      z: 2.3
    elevator_door_size:
      x: 0.16
      y: 1.1
      z: 2.1
    outside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
    inside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0.25 # inside y axis offset (0.25 means left 25cm)
        z: 0
        w: -90 # inside rotate degrees (-90 means right side)
  - id: 1
    elevator_size:
      x: 1.6
      y: 1.6
      z: 2.3
    elevator_door_size:
      x: 0.16
      y: 1.1
      z: 2.1
    outside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
    inside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: -0.25 # inside y axis offset (0.25 means right 25cm)
        z: 0
        w: 90