building: 'csl'
elevators:
  - id: 0
    elevator_size:
      x: 1.49
      y: 1.64
      z: 2.3
    elevator_door_size:
      x: 0.26
      y: 0.9
      z: 2.1
    outside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
    inside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: -75 #-70 degrees right side
  - id: 1
    elevator_size:
      x: 1.33
      y: 2.04
      z: 2.3
    elevator_door_size:
      x: 0.26
      y: 1.1
      z: 2.1
    outside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
    inside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: -75 #70 degrees left side