building: 'itc'
elevators:
  - id: 0
    elevator_size:
      x: 1.34
      y: 1.4
      z: 2.3
    elevator_door_size:
      x: 0.29
      y: 0.8
      z: 2.1
    outside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
    inside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: -75 #-70 degrees right side
  - id: 1
    elevator_size:
      x: 1.34
      y: 1.4
      z: 2.3
    elevator_door_size:
      x: 0.29
      y: 0.8
      z: 2.1
    outside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
    inside_button_position:
      position:
        x: 0
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 90 #70 degrees left side