# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from campusrover_msgs/InDemoStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import campusrover_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class InDemoStatus(genpy.Message):
  _md5sum = "34ab88de0bd0120458bb8839561e2f23"
  _type = "campusrover_msgs/InDemoStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String status
std_msgs/String controller
campusrover_msgs/PoseWithId target_pose_data
campusrover_msgs/PoseWithId current_pose_data
campusrover_msgs/PoseWithId mid_target_pose_data
================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: campusrover_msgs/PoseWithId
std_msgs/String id
std_msgs/String type
std_msgs/Int16 floor
geometry_msgs/PoseStamped pose

================================================================================
MSG: std_msgs/Int16
int16 data

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['status','controller','target_pose_data','current_pose_data','mid_target_pose_data']
  _slot_types = ['std_msgs/String','std_msgs/String','campusrover_msgs/PoseWithId','campusrover_msgs/PoseWithId','campusrover_msgs/PoseWithId']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status,controller,target_pose_data,current_pose_data,mid_target_pose_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InDemoStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.status is None:
        self.status = std_msgs.msg.String()
      if self.controller is None:
        self.controller = std_msgs.msg.String()
      if self.target_pose_data is None:
        self.target_pose_data = campusrover_msgs.msg.PoseWithId()
      if self.current_pose_data is None:
        self.current_pose_data = campusrover_msgs.msg.PoseWithId()
      if self.mid_target_pose_data is None:
        self.mid_target_pose_data = campusrover_msgs.msg.PoseWithId()
    else:
      self.status = std_msgs.msg.String()
      self.controller = std_msgs.msg.String()
      self.target_pose_data = campusrover_msgs.msg.PoseWithId()
      self.current_pose_data = campusrover_msgs.msg.PoseWithId()
      self.mid_target_pose_data = campusrover_msgs.msg.PoseWithId()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.controller.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target_pose_data.id.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target_pose_data.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_h3I().pack(_x.target_pose_data.floor.data, _x.target_pose_data.pose.header.seq, _x.target_pose_data.pose.header.stamp.secs, _x.target_pose_data.pose.header.stamp.nsecs))
      _x = self.target_pose_data.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.target_pose_data.pose.pose.position.x, _x.target_pose_data.pose.pose.position.y, _x.target_pose_data.pose.pose.position.z, _x.target_pose_data.pose.pose.orientation.x, _x.target_pose_data.pose.pose.orientation.y, _x.target_pose_data.pose.pose.orientation.z, _x.target_pose_data.pose.pose.orientation.w))
      _x = self.current_pose_data.id.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.current_pose_data.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_h3I().pack(_x.current_pose_data.floor.data, _x.current_pose_data.pose.header.seq, _x.current_pose_data.pose.header.stamp.secs, _x.current_pose_data.pose.header.stamp.nsecs))
      _x = self.current_pose_data.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.current_pose_data.pose.pose.position.x, _x.current_pose_data.pose.pose.position.y, _x.current_pose_data.pose.pose.position.z, _x.current_pose_data.pose.pose.orientation.x, _x.current_pose_data.pose.pose.orientation.y, _x.current_pose_data.pose.pose.orientation.z, _x.current_pose_data.pose.pose.orientation.w))
      _x = self.mid_target_pose_data.id.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mid_target_pose_data.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_h3I().pack(_x.mid_target_pose_data.floor.data, _x.mid_target_pose_data.pose.header.seq, _x.mid_target_pose_data.pose.header.stamp.secs, _x.mid_target_pose_data.pose.header.stamp.nsecs))
      _x = self.mid_target_pose_data.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.mid_target_pose_data.pose.pose.position.x, _x.mid_target_pose_data.pose.pose.position.y, _x.mid_target_pose_data.pose.pose.position.z, _x.mid_target_pose_data.pose.pose.orientation.x, _x.mid_target_pose_data.pose.pose.orientation.y, _x.mid_target_pose_data.pose.pose.orientation.z, _x.mid_target_pose_data.pose.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.status is None:
        self.status = std_msgs.msg.String()
      if self.controller is None:
        self.controller = std_msgs.msg.String()
      if self.target_pose_data is None:
        self.target_pose_data = campusrover_msgs.msg.PoseWithId()
      if self.current_pose_data is None:
        self.current_pose_data = campusrover_msgs.msg.PoseWithId()
      if self.mid_target_pose_data is None:
        self.mid_target_pose_data = campusrover_msgs.msg.PoseWithId()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.controller.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.controller.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_pose_data.id.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_pose_data.id.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_pose_data.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_pose_data.type.data = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.target_pose_data.floor.data, _x.target_pose_data.pose.header.seq, _x.target_pose_data.pose.header.stamp.secs, _x.target_pose_data.pose.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_pose_data.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_pose_data.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.target_pose_data.pose.pose.position.x, _x.target_pose_data.pose.pose.position.y, _x.target_pose_data.pose.pose.position.z, _x.target_pose_data.pose.pose.orientation.x, _x.target_pose_data.pose.pose.orientation.y, _x.target_pose_data.pose.pose.orientation.z, _x.target_pose_data.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_pose_data.id.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_pose_data.id.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_pose_data.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_pose_data.type.data = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.current_pose_data.floor.data, _x.current_pose_data.pose.header.seq, _x.current_pose_data.pose.header.stamp.secs, _x.current_pose_data.pose.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_pose_data.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_pose_data.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.current_pose_data.pose.pose.position.x, _x.current_pose_data.pose.pose.position.y, _x.current_pose_data.pose.pose.position.z, _x.current_pose_data.pose.pose.orientation.x, _x.current_pose_data.pose.pose.orientation.y, _x.current_pose_data.pose.pose.orientation.z, _x.current_pose_data.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mid_target_pose_data.id.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mid_target_pose_data.id.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mid_target_pose_data.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mid_target_pose_data.type.data = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.mid_target_pose_data.floor.data, _x.mid_target_pose_data.pose.header.seq, _x.mid_target_pose_data.pose.header.stamp.secs, _x.mid_target_pose_data.pose.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mid_target_pose_data.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mid_target_pose_data.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.mid_target_pose_data.pose.pose.position.x, _x.mid_target_pose_data.pose.pose.position.y, _x.mid_target_pose_data.pose.pose.position.z, _x.mid_target_pose_data.pose.pose.orientation.x, _x.mid_target_pose_data.pose.pose.orientation.y, _x.mid_target_pose_data.pose.pose.orientation.z, _x.mid_target_pose_data.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.controller.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target_pose_data.id.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target_pose_data.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_h3I().pack(_x.target_pose_data.floor.data, _x.target_pose_data.pose.header.seq, _x.target_pose_data.pose.header.stamp.secs, _x.target_pose_data.pose.header.stamp.nsecs))
      _x = self.target_pose_data.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.target_pose_data.pose.pose.position.x, _x.target_pose_data.pose.pose.position.y, _x.target_pose_data.pose.pose.position.z, _x.target_pose_data.pose.pose.orientation.x, _x.target_pose_data.pose.pose.orientation.y, _x.target_pose_data.pose.pose.orientation.z, _x.target_pose_data.pose.pose.orientation.w))
      _x = self.current_pose_data.id.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.current_pose_data.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_h3I().pack(_x.current_pose_data.floor.data, _x.current_pose_data.pose.header.seq, _x.current_pose_data.pose.header.stamp.secs, _x.current_pose_data.pose.header.stamp.nsecs))
      _x = self.current_pose_data.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.current_pose_data.pose.pose.position.x, _x.current_pose_data.pose.pose.position.y, _x.current_pose_data.pose.pose.position.z, _x.current_pose_data.pose.pose.orientation.x, _x.current_pose_data.pose.pose.orientation.y, _x.current_pose_data.pose.pose.orientation.z, _x.current_pose_data.pose.pose.orientation.w))
      _x = self.mid_target_pose_data.id.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mid_target_pose_data.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_h3I().pack(_x.mid_target_pose_data.floor.data, _x.mid_target_pose_data.pose.header.seq, _x.mid_target_pose_data.pose.header.stamp.secs, _x.mid_target_pose_data.pose.header.stamp.nsecs))
      _x = self.mid_target_pose_data.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.mid_target_pose_data.pose.pose.position.x, _x.mid_target_pose_data.pose.pose.position.y, _x.mid_target_pose_data.pose.pose.position.z, _x.mid_target_pose_data.pose.pose.orientation.x, _x.mid_target_pose_data.pose.pose.orientation.y, _x.mid_target_pose_data.pose.pose.orientation.z, _x.mid_target_pose_data.pose.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.status is None:
        self.status = std_msgs.msg.String()
      if self.controller is None:
        self.controller = std_msgs.msg.String()
      if self.target_pose_data is None:
        self.target_pose_data = campusrover_msgs.msg.PoseWithId()
      if self.current_pose_data is None:
        self.current_pose_data = campusrover_msgs.msg.PoseWithId()
      if self.mid_target_pose_data is None:
        self.mid_target_pose_data = campusrover_msgs.msg.PoseWithId()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.controller.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.controller.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_pose_data.id.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_pose_data.id.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_pose_data.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_pose_data.type.data = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.target_pose_data.floor.data, _x.target_pose_data.pose.header.seq, _x.target_pose_data.pose.header.stamp.secs, _x.target_pose_data.pose.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_pose_data.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_pose_data.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.target_pose_data.pose.pose.position.x, _x.target_pose_data.pose.pose.position.y, _x.target_pose_data.pose.pose.position.z, _x.target_pose_data.pose.pose.orientation.x, _x.target_pose_data.pose.pose.orientation.y, _x.target_pose_data.pose.pose.orientation.z, _x.target_pose_data.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_pose_data.id.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_pose_data.id.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_pose_data.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_pose_data.type.data = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.current_pose_data.floor.data, _x.current_pose_data.pose.header.seq, _x.current_pose_data.pose.header.stamp.secs, _x.current_pose_data.pose.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_pose_data.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.current_pose_data.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.current_pose_data.pose.pose.position.x, _x.current_pose_data.pose.pose.position.y, _x.current_pose_data.pose.pose.position.z, _x.current_pose_data.pose.pose.orientation.x, _x.current_pose_data.pose.pose.orientation.y, _x.current_pose_data.pose.pose.orientation.z, _x.current_pose_data.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mid_target_pose_data.id.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mid_target_pose_data.id.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mid_target_pose_data.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mid_target_pose_data.type.data = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.mid_target_pose_data.floor.data, _x.mid_target_pose_data.pose.header.seq, _x.mid_target_pose_data.pose.header.stamp.secs, _x.mid_target_pose_data.pose.header.stamp.nsecs,) = _get_struct_h3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mid_target_pose_data.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mid_target_pose_data.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.mid_target_pose_data.pose.pose.position.x, _x.mid_target_pose_data.pose.pose.position.y, _x.mid_target_pose_data.pose.pose.position.z, _x.mid_target_pose_data.pose.pose.orientation.x, _x.mid_target_pose_data.pose.pose.orientation.y, _x.mid_target_pose_data.pose.pose.orientation.z, _x.mid_target_pose_data.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_h3I = None
def _get_struct_h3I():
    global _struct_h3I
    if _struct_h3I is None:
        _struct_h3I = struct.Struct("<h3I")
    return _struct_h3I
