/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) campusrover_model_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[26] = {9, 7, 0, 4, 8, 10, 11, 12, 14, 16, 0, 1, 2, 4, 0, 1, 3, 4, 1, 4, 0, 1, 0, 5, 1, 6};
static const casadi_int casadi_s4[20] = {9, 9, 0, 2, 5, 5, 5, 8, 8, 8, 8, 8, 1, 4, 0, 1, 4, 0, 1, 4};

/* campusrover_model_dyn_disc_phi_fun_jac_hess:(i0[7],i1[2],i2[7],i3[12])->(o0[7],o1[9x7,16nz],o2[9x9,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=2.0000000000000001e-01;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1*a2);
  a4=arg[1]? arg[1][1] : 0;
  a5=(a1*a4);
  a6=2.;
  a5=(a5/a6);
  a7=cos(a5);
  a8=(a3*a7);
  a9=arg[0]? arg[0][2] : 0;
  a10=cos(a9);
  a11=(a8*a10);
  a12=(a1*a2);
  a13=(a1*a4);
  a13=(a13/a6);
  a6=sin(a13);
  a14=(a12*a6);
  a15=sin(a9);
  a16=(a14*a15);
  a11=(a11-a16);
  a0=(a0+a11);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a11=sin(a9);
  a16=(a8*a11);
  a17=cos(a9);
  a18=(a14*a17);
  a16=(a16+a18);
  a0=(a0+a16);
  if (res[0]!=0) res[0][1]=a0;
  a0=(a1*a4);
  a0=(a9+a0);
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a2;
  if (res[0]!=0) res[0][4]=a4;
  a0=arg[0]? arg[0][3] : 0;
  a2=(a2-a0);
  a2=(a2/a1);
  if (res[0]!=0) res[0][5]=a2;
  a2=arg[0]? arg[0][4] : 0;
  a4=(a4-a2);
  a4=(a4/a1);
  if (res[0]!=0) res[0][6]=a4;
  a4=(a1*a7);
  a2=(a10*a4);
  a0=(a1*a6);
  a16=(a15*a0);
  a2=(a2-a16);
  if (res[1]!=0) res[1][0]=a2;
  a2=1.0000000000000001e-01;
  a16=sin(a5);
  a16=(a2*a16);
  a16=(a3*a16);
  a18=(a10*a16);
  a19=cos(a13);
  a19=(a2*a19);
  a19=(a12*a19);
  a20=(a15*a19);
  a18=(a18+a20);
  a18=(-a18);
  if (res[1]!=0) res[1][1]=a18;
  a18=1.;
  if (res[1]!=0) res[1][2]=a18;
  a20=sin(a9);
  a20=(a8*a20);
  a21=cos(a9);
  a21=(a14*a21);
  a20=(a20+a21);
  a20=(-a20);
  if (res[1]!=0) res[1][3]=a20;
  a4=(a11*a4);
  a0=(a17*a0);
  a4=(a4+a0);
  if (res[1]!=0) res[1][4]=a4;
  a19=(a17*a19);
  a16=(a11*a16);
  a19=(a19-a16);
  if (res[1]!=0) res[1][5]=a19;
  if (res[1]!=0) res[1][6]=a18;
  a19=cos(a9);
  a19=(a8*a19);
  a16=sin(a9);
  a16=(a14*a16);
  a19=(a19-a16);
  if (res[1]!=0) res[1][7]=a19;
  if (res[1]!=0) res[1][8]=a1;
  if (res[1]!=0) res[1][9]=a18;
  if (res[1]!=0) res[1][10]=a18;
  if (res[1]!=0) res[1][11]=a18;
  a18=5.;
  if (res[1]!=0) res[1][12]=a18;
  a19=-5.;
  if (res[1]!=0) res[1][13]=a19;
  if (res[1]!=0) res[1][14]=a18;
  if (res[1]!=0) res[1][15]=a19;
  a19=5.0000000000000000e-01;
  a18=cos(a13);
  a16=arg[2]? arg[2][1] : 0;
  a17=(a17*a16);
  a4=arg[2]? arg[2][0] : 0;
  a15=(a15*a4);
  a17=(a17-a15);
  a15=(a1*a17);
  a15=(a18*a15);
  a15=(a19*a15);
  a15=(a1*a15);
  a0=sin(a5);
  a11=(a11*a16);
  a10=(a10*a4);
  a11=(a11+a10);
  a10=(a1*a11);
  a10=(a0*a10);
  a10=(a19*a10);
  a10=(a1*a10);
  a15=(a15-a10);
  if (res[2]!=0) res[2][0]=a15;
  a15=cos(a9);
  a10=(a1*a7);
  a20=(a16*a10);
  a20=(a15*a20);
  a21=sin(a9);
  a22=(a1*a6);
  a23=(a16*a22);
  a23=(a21*a23);
  a20=(a20-a23);
  a23=cos(a9);
  a22=(a4*a22);
  a22=(a23*a22);
  a20=(a20-a22);
  a22=sin(a9);
  a10=(a4*a10);
  a10=(a22*a10);
  a20=(a20-a10);
  if (res[2]!=0) res[2][1]=a20;
  a20=cos(a13);
  a20=(a2*a20);
  a10=(a17*a20);
  a10=(a1*a10);
  a24=sin(a5);
  a24=(a2*a24);
  a25=(a11*a24);
  a25=(a1*a25);
  a10=(a10-a25);
  if (res[2]!=0) res[2][2]=a10;
  a17=(a12*a17);
  a13=sin(a13);
  a13=(a2*a13);
  a17=(a17*a13);
  a17=(a19*a17);
  a17=(a1*a17);
  a11=(a3*a11);
  a5=cos(a5);
  a2=(a2*a5);
  a11=(a11*a2);
  a11=(a19*a11);
  a11=(a1*a11);
  a17=(a17+a11);
  a17=(-a17);
  if (res[2]!=0) res[2][3]=a17;
  a24=(a3*a24);
  a17=(a4*a24);
  a22=(a22*a17);
  a20=(a12*a20);
  a17=(a16*a20);
  a21=(a21*a17);
  a24=(a16*a24);
  a15=(a15*a24);
  a21=(a21+a15);
  a20=(a4*a20);
  a23=(a23*a20);
  a21=(a21+a23);
  a22=(a22-a21);
  if (res[2]!=0) res[2][4]=a22;
  a22=cos(a9);
  a22=(a16*a22);
  a21=sin(a9);
  a21=(a4*a21);
  a22=(a22-a21);
  a7=(a7*a22);
  a7=(a1*a7);
  a21=sin(a9);
  a21=(a16*a21);
  a23=cos(a9);
  a23=(a4*a23);
  a21=(a21+a23);
  a6=(a6*a21);
  a6=(a1*a6);
  a7=(a7-a6);
  if (res[2]!=0) res[2][5]=a7;
  a12=(a12*a21);
  a18=(a18*a12);
  a18=(a19*a18);
  a18=(a1*a18);
  a3=(a3*a22);
  a0=(a0*a3);
  a19=(a19*a0);
  a1=(a1*a19);
  a18=(a18+a1);
  a18=(-a18);
  if (res[2]!=0) res[2][6]=a18;
  a18=(a14*a4);
  a1=sin(a9);
  a18=(a18*a1);
  a14=(a14*a16);
  a1=cos(a9);
  a14=(a14*a1);
  a16=(a8*a16);
  a1=sin(a9);
  a16=(a16*a1);
  a14=(a14+a16);
  a18=(a18-a14);
  a8=(a8*a4);
  a9=cos(a9);
  a8=(a8*a9);
  a18=(a18-a8);
  if (res[2]!=0) res[2][7]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int campusrover_model_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int campusrover_model_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int campusrover_model_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void campusrover_model_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int campusrover_model_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void campusrover_model_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void campusrover_model_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void campusrover_model_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int campusrover_model_dyn_disc_phi_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int campusrover_model_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real campusrover_model_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* campusrover_model_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* campusrover_model_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* campusrover_model_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* campusrover_model_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int campusrover_model_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
