// Generated by gencpp from file campusrover_msgs/ActionCharging.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_ACTIONCHARGING_H
#define CAMPUSROVER_MSGS_MESSAGE_ACTIONCHARGING_H

#include <ros/service_traits.h>


#include <campusrover_msgs/ActionChargingRequest.h>
#include <campusrover_msgs/ActionChargingResponse.h>


namespace campusrover_msgs
{

struct ActionCharging
{

typedef ActionChargingRequest Request;
typedef ActionChargingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionCharging
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::ActionCharging > {
  static const char* value()
  {
    return "5168c6de9ca46f7222d4c5d4011956cc";
  }

  static const char* value(const ::campusrover_msgs::ActionCharging&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::ActionCharging > {
  static const char* value()
  {
    return "campusrover_msgs/ActionCharging";
  }

  static const char* value(const ::campusrover_msgs::ActionCharging&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::ActionChargingRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::ActionCharging >
template<>
struct MD5Sum< ::campusrover_msgs::ActionChargingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ActionCharging >::value();
  }
  static const char* value(const ::campusrover_msgs::ActionChargingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ActionChargingRequest> should match
// service_traits::DataType< ::campusrover_msgs::ActionCharging >
template<>
struct DataType< ::campusrover_msgs::ActionChargingRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ActionCharging >::value();
  }
  static const char* value(const ::campusrover_msgs::ActionChargingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::ActionChargingResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::ActionCharging >
template<>
struct MD5Sum< ::campusrover_msgs::ActionChargingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ActionCharging >::value();
  }
  static const char* value(const ::campusrover_msgs::ActionChargingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ActionChargingResponse> should match
// service_traits::DataType< ::campusrover_msgs::ActionCharging >
template<>
struct DataType< ::campusrover_msgs::ActionChargingResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ActionCharging >::value();
  }
  static const char* value(const ::campusrover_msgs::ActionChargingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_ACTIONCHARGING_H
