// Generated by gencpp from file campusrover_msgs/ArmTableHomeReturn.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_ARMTABLEHOMERETURN_H
#define CAMPUSROVER_MSGS_MESSAGE_ARMTABLEHOMERETURN_H

#include <ros/service_traits.h>


#include <campusrover_msgs/ArmTableHomeReturnRequest.h>
#include <campusrover_msgs/ArmTableHomeReturnResponse.h>


namespace campusrover_msgs
{

struct ArmTableHomeReturn
{

typedef ArmTableHomeReturnRequest Request;
typedef ArmTableHomeReturnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmTableHomeReturn
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::ArmTableHomeReturn > {
  static const char* value()
  {
    return "24842bc754e0f5cc982338eca1269251";
  }

  static const char* value(const ::campusrover_msgs::ArmTableHomeReturn&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::ArmTableHomeReturn > {
  static const char* value()
  {
    return "campusrover_msgs/ArmTableHomeReturn";
  }

  static const char* value(const ::campusrover_msgs::ArmTableHomeReturn&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::ArmTableHomeReturnRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::ArmTableHomeReturn >
template<>
struct MD5Sum< ::campusrover_msgs::ArmTableHomeReturnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ArmTableHomeReturn >::value();
  }
  static const char* value(const ::campusrover_msgs::ArmTableHomeReturnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ArmTableHomeReturnRequest> should match
// service_traits::DataType< ::campusrover_msgs::ArmTableHomeReturn >
template<>
struct DataType< ::campusrover_msgs::ArmTableHomeReturnRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ArmTableHomeReturn >::value();
  }
  static const char* value(const ::campusrover_msgs::ArmTableHomeReturnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::ArmTableHomeReturnResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::ArmTableHomeReturn >
template<>
struct MD5Sum< ::campusrover_msgs::ArmTableHomeReturnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ArmTableHomeReturn >::value();
  }
  static const char* value(const ::campusrover_msgs::ArmTableHomeReturnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ArmTableHomeReturnResponse> should match
// service_traits::DataType< ::campusrover_msgs::ArmTableHomeReturn >
template<>
struct DataType< ::campusrover_msgs::ArmTableHomeReturnResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ArmTableHomeReturn >::value();
  }
  static const char* value(const ::campusrover_msgs::ArmTableHomeReturnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_ARMTABLEHOMERETURN_H
