// Generated by gencpp from file campusrover_msgs/BubbleMPC.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_BUBBLEMPC_H
#define CAMPUSROVER_MSGS_MESSAGE_BUBBLEMPC_H

#include <ros/service_traits.h>


#include <campusrover_msgs/BubbleMPCRequest.h>
#include <campusrover_msgs/BubbleMPCResponse.h>


namespace campusrover_msgs
{

struct BubbleMPC
{

typedef BubbleMPCRequest Request;
typedef BubbleMPCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BubbleMPC
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::BubbleMPC > {
  static const char* value()
  {
    return "5673ff572d37b8731f5b0a01e168ccd0";
  }

  static const char* value(const ::campusrover_msgs::BubbleMPC&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::BubbleMPC > {
  static const char* value()
  {
    return "campusrover_msgs/BubbleMPC";
  }

  static const char* value(const ::campusrover_msgs::BubbleMPC&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::BubbleMPCRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::BubbleMPC >
template<>
struct MD5Sum< ::campusrover_msgs::BubbleMPCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::BubbleMPC >::value();
  }
  static const char* value(const ::campusrover_msgs::BubbleMPCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::BubbleMPCRequest> should match
// service_traits::DataType< ::campusrover_msgs::BubbleMPC >
template<>
struct DataType< ::campusrover_msgs::BubbleMPCRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::BubbleMPC >::value();
  }
  static const char* value(const ::campusrover_msgs::BubbleMPCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::BubbleMPCResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::BubbleMPC >
template<>
struct MD5Sum< ::campusrover_msgs::BubbleMPCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::BubbleMPC >::value();
  }
  static const char* value(const ::campusrover_msgs::BubbleMPCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::BubbleMPCResponse> should match
// service_traits::DataType< ::campusrover_msgs::BubbleMPC >
template<>
struct DataType< ::campusrover_msgs::BubbleMPCResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::BubbleMPC >::value();
  }
  static const char* value(const ::campusrover_msgs::BubbleMPCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_BUBBLEMPC_H
