// Generated by gencpp from file campusrover_msgs/BubbleMPCResponse.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_BUBBLEMPCRESPONSE_H
#define CAMPUSROVER_MSGS_MESSAGE_BUBBLEMPCRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct BubbleMPCResponse_
{
  typedef BubbleMPCResponse_<ContainerAllocator> Type;

  BubbleMPCResponse_()
    : msg()  {
    }
  BubbleMPCResponse_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BubbleMPCResponse_

typedef ::campusrover_msgs::BubbleMPCResponse_<std::allocator<void> > BubbleMPCResponse;

typedef boost::shared_ptr< ::campusrover_msgs::BubbleMPCResponse > BubbleMPCResponsePtr;
typedef boost::shared_ptr< ::campusrover_msgs::BubbleMPCResponse const> BubbleMPCResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator1> & lhs, const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator2> & rhs)
{
  return lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator1> & lhs, const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d96ed7307768047ULL;
  static const uint64_t static_value2 = 0x54140b85e64c862eULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/BubbleMPCResponse";
  }

  static const char* value(const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg\n"
;
  }

  static const char* value(const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BubbleMPCResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::BubbleMPCResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_BUBBLEMPCRESPONSE_H
