// Generated by gencpp from file campusrover_msgs/ButtonPoses.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_BUTTONPOSES_H
#define CAMPUSROVER_MSGS_MESSAGE_BUTTONPOSES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <campusrover_msgs/ButtonPose.h>

namespace campusrover_msgs
{
template <class ContainerAllocator>
struct ButtonPoses_
{
  typedef ButtonPoses_<ContainerAllocator> Type;

  ButtonPoses_()
    : header()
    , button_poses()  {
    }
  ButtonPoses_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , button_poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::campusrover_msgs::ButtonPose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::campusrover_msgs::ButtonPose_<ContainerAllocator> >> _button_poses_type;
  _button_poses_type button_poses;





  typedef boost::shared_ptr< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonPoses_

typedef ::campusrover_msgs::ButtonPoses_<std::allocator<void> > ButtonPoses;

typedef boost::shared_ptr< ::campusrover_msgs::ButtonPoses > ButtonPosesPtr;
typedef boost::shared_ptr< ::campusrover_msgs::ButtonPoses const> ButtonPosesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::ButtonPoses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::ButtonPoses_<ContainerAllocator1> & lhs, const ::campusrover_msgs::ButtonPoses_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.button_poses == rhs.button_poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::ButtonPoses_<ContainerAllocator1> & lhs, const ::campusrover_msgs::ButtonPoses_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01d1633c8e2cd27ca2e62eb14d3836b3";
  }

  static const char* value(const ::campusrover_msgs::ButtonPoses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01d1633c8e2cd27cULL;
  static const uint64_t static_value2 = 0xa2e62eb14d3836b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/ButtonPoses";
  }

  static const char* value(const ::campusrover_msgs::ButtonPoses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"campusrover_msgs/ButtonPose[] button_poses\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: campusrover_msgs/ButtonPose\n"
"string label\n"
"geometry_msgs/Pose pose\n"
"float32 activation\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::campusrover_msgs::ButtonPoses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.button_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonPoses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::ButtonPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::ButtonPoses_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "button_poses[]" << std::endl;
    for (size_t i = 0; i < v.button_poses.size(); ++i)
    {
      s << indent << "  button_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::campusrover_msgs::ButtonPose_<ContainerAllocator> >::stream(s, indent + "    ", v.button_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_BUTTONPOSES_H
