// Generated by gencpp from file campusrover_msgs/ButtonStatus.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_BUTTONSTATUS_H
#define CAMPUSROVER_MSGS_MESSAGE_BUTTONSTATUS_H

#include <ros/service_traits.h>


#include <campusrover_msgs/ButtonStatusRequest.h>
#include <campusrover_msgs/ButtonStatusResponse.h>


namespace campusrover_msgs
{

struct ButtonStatus
{

typedef ButtonStatusRequest Request;
typedef ButtonStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ButtonStatus
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::ButtonStatus > {
  static const char* value()
  {
    return "5eabfc9879043ecc49b3481670b2286f";
  }

  static const char* value(const ::campusrover_msgs::ButtonStatus&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::ButtonStatus > {
  static const char* value()
  {
    return "campusrover_msgs/ButtonStatus";
  }

  static const char* value(const ::campusrover_msgs::ButtonStatus&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::ButtonStatusRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::ButtonStatus >
template<>
struct MD5Sum< ::campusrover_msgs::ButtonStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ButtonStatus >::value();
  }
  static const char* value(const ::campusrover_msgs::ButtonStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ButtonStatusRequest> should match
// service_traits::DataType< ::campusrover_msgs::ButtonStatus >
template<>
struct DataType< ::campusrover_msgs::ButtonStatusRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ButtonStatus >::value();
  }
  static const char* value(const ::campusrover_msgs::ButtonStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::ButtonStatusResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::ButtonStatus >
template<>
struct MD5Sum< ::campusrover_msgs::ButtonStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ButtonStatus >::value();
  }
  static const char* value(const ::campusrover_msgs::ButtonStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ButtonStatusResponse> should match
// service_traits::DataType< ::campusrover_msgs::ButtonStatus >
template<>
struct DataType< ::campusrover_msgs::ButtonStatusResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ButtonStatus >::value();
  }
  static const char* value(const ::campusrover_msgs::ButtonStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_BUTTONSTATUS_H
