// Generated by gencpp from file campusrover_msgs/ChargerStatus.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_CHARGERSTATUS_H
#define CAMPUSROVER_MSGS_MESSAGE_CHARGERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct ChargerStatus_
{
  typedef ChargerStatus_<ContainerAllocator> Type;

  ChargerStatus_()
    : status(0)  {
    }
  ChargerStatus_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOEN)
  #undef UNKNOEN
#endif
#if defined(_WIN32) && defined(CONNECTED)
  #undef CONNECTED
#endif
#if defined(_WIN32) && defined(UNCONNECTED)
  #undef UNCONNECTED
#endif

  enum {
    UNKNOEN = 0u,
    CONNECTED = 1u,
    UNCONNECTED = 2u,
  };


  typedef boost::shared_ptr< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ChargerStatus_

typedef ::campusrover_msgs::ChargerStatus_<std::allocator<void> > ChargerStatus;

typedef boost::shared_ptr< ::campusrover_msgs::ChargerStatus > ChargerStatusPtr;
typedef boost::shared_ptr< ::campusrover_msgs::ChargerStatus const> ChargerStatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::ChargerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::ChargerStatus_<ContainerAllocator1> & lhs, const ::campusrover_msgs::ChargerStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::ChargerStatus_<ContainerAllocator1> & lhs, const ::campusrover_msgs::ChargerStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11eb00a286eb748ac3d666ae0507cfc9";
  }

  static const char* value(const ::campusrover_msgs::ChargerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11eb00a286eb748aULL;
  static const uint64_t static_value2 = 0xc3d666ae0507cfc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/ChargerStatus";
  }

  static const char* value(const ::campusrover_msgs::ChargerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 UNKNOEN = 0\n"
"uint8 CONNECTED = 1\n"
"uint8 UNCONNECTED = 2\n"
"uint8 status\n"
;
  }

  static const char* value(const ::campusrover_msgs::ChargerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::ChargerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::ChargerStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_CHARGERSTATUS_H
