// Generated by gencpp from file campusrover_msgs/ElevatorInfoReader.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_ELEVATORINFOREADER_H
#define CAMPUSROVER_MSGS_MESSAGE_ELEVATORINFOREADER_H

#include <ros/service_traits.h>


#include <campusrover_msgs/ElevatorInfoReaderRequest.h>
#include <campusrover_msgs/ElevatorInfoReaderResponse.h>


namespace campusrover_msgs
{

struct ElevatorInfoReader
{

typedef ElevatorInfoReaderRequest Request;
typedef ElevatorInfoReaderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ElevatorInfoReader
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::ElevatorInfoReader > {
  static const char* value()
  {
    return "5b0fce0ae6e42e7d4a2cd3e0f8048504";
  }

  static const char* value(const ::campusrover_msgs::ElevatorInfoReader&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::ElevatorInfoReader > {
  static const char* value()
  {
    return "campusrover_msgs/ElevatorInfoReader";
  }

  static const char* value(const ::campusrover_msgs::ElevatorInfoReader&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::ElevatorInfoReaderRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::ElevatorInfoReader >
template<>
struct MD5Sum< ::campusrover_msgs::ElevatorInfoReaderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ElevatorInfoReader >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorInfoReaderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ElevatorInfoReaderRequest> should match
// service_traits::DataType< ::campusrover_msgs::ElevatorInfoReader >
template<>
struct DataType< ::campusrover_msgs::ElevatorInfoReaderRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ElevatorInfoReader >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorInfoReaderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::ElevatorInfoReaderResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::ElevatorInfoReader >
template<>
struct MD5Sum< ::campusrover_msgs::ElevatorInfoReaderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ElevatorInfoReader >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorInfoReaderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ElevatorInfoReaderResponse> should match
// service_traits::DataType< ::campusrover_msgs::ElevatorInfoReader >
template<>
struct DataType< ::campusrover_msgs::ElevatorInfoReaderResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ElevatorInfoReader >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorInfoReaderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_ELEVATORINFOREADER_H
