// Generated by gencpp from file campusrover_msgs/ElevatorStatusChecker.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_ELEVATORSTATUSCHECKER_H
#define CAMPUSROVER_MSGS_MESSAGE_ELEVATORSTATUSCHECKER_H

#include <ros/service_traits.h>


#include <campusrover_msgs/ElevatorStatusCheckerRequest.h>
#include <campusrover_msgs/ElevatorStatusCheckerResponse.h>


namespace campusrover_msgs
{

struct ElevatorStatusChecker
{

typedef ElevatorStatusCheckerRequest Request;
typedef ElevatorStatusCheckerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ElevatorStatusChecker
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::ElevatorStatusChecker > {
  static const char* value()
  {
    return "10f198604c5b4593b82d50b6435659cb";
  }

  static const char* value(const ::campusrover_msgs::ElevatorStatusChecker&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::ElevatorStatusChecker > {
  static const char* value()
  {
    return "campusrover_msgs/ElevatorStatusChecker";
  }

  static const char* value(const ::campusrover_msgs::ElevatorStatusChecker&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::ElevatorStatusCheckerRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::ElevatorStatusChecker >
template<>
struct MD5Sum< ::campusrover_msgs::ElevatorStatusCheckerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ElevatorStatusChecker >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorStatusCheckerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ElevatorStatusCheckerRequest> should match
// service_traits::DataType< ::campusrover_msgs::ElevatorStatusChecker >
template<>
struct DataType< ::campusrover_msgs::ElevatorStatusCheckerRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ElevatorStatusChecker >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorStatusCheckerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::ElevatorStatusCheckerResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::ElevatorStatusChecker >
template<>
struct MD5Sum< ::campusrover_msgs::ElevatorStatusCheckerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ElevatorStatusChecker >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorStatusCheckerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ElevatorStatusCheckerResponse> should match
// service_traits::DataType< ::campusrover_msgs::ElevatorStatusChecker >
template<>
struct DataType< ::campusrover_msgs::ElevatorStatusCheckerResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ElevatorStatusChecker >::value();
  }
  static const char* value(const ::campusrover_msgs::ElevatorStatusCheckerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_ELEVATORSTATUSCHECKER_H
