// Generated by gencpp from file campusrover_msgs/ElevatorInfoReaderRequest.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_ELEVATORINFOREADERREQUEST_H
#define CAMPUSROVER_MSGS_MESSAGE_ELEVATORINFOREADERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct ElevatorInfoReaderRequest_
{
  typedef ElevatorInfoReaderRequest_<ContainerAllocator> Type;

  ElevatorInfoReaderRequest_()
    : building()
    , elevator_id(0)  {
    }
  ElevatorInfoReaderRequest_(const ContainerAllocator& _alloc)
    : building(_alloc)
    , elevator_id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _building_type;
  _building_type building;

   typedef int8_t _elevator_id_type;
  _elevator_id_type elevator_id;





  typedef boost::shared_ptr< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ElevatorInfoReaderRequest_

typedef ::campusrover_msgs::ElevatorInfoReaderRequest_<std::allocator<void> > ElevatorInfoReaderRequest;

typedef boost::shared_ptr< ::campusrover_msgs::ElevatorInfoReaderRequest > ElevatorInfoReaderRequestPtr;
typedef boost::shared_ptr< ::campusrover_msgs::ElevatorInfoReaderRequest const> ElevatorInfoReaderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.building == rhs.building &&
    lhs.elevator_id == rhs.elevator_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6355ffc837f90aefb88f1c73ab16c96";
  }

  static const char* value(const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6355ffc837f90aeULL;
  static const uint64_t static_value2 = 0xfb88f1c73ab16c96ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/ElevatorInfoReaderRequest";
  }

  static const char* value(const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string building\n"
"int8 elevator_id\n"
;
  }

  static const char* value(const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.building);
      stream.next(m.elevator_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ElevatorInfoReaderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::ElevatorInfoReaderRequest_<ContainerAllocator>& v)
  {
    s << indent << "building: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.building);
    s << indent << "elevator_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.elevator_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_ELEVATORINFOREADERREQUEST_H
