// Generated by gencpp from file campusrover_msgs/InitFloor.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_INITFLOOR_H
#define CAMPUSROVER_MSGS_MESSAGE_INITFLOOR_H

#include <ros/service_traits.h>


#include <campusrover_msgs/InitFloorRequest.h>
#include <campusrover_msgs/InitFloorResponse.h>


namespace campusrover_msgs
{

struct InitFloor
{

typedef InitFloorRequest Request;
typedef InitFloorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitFloor
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::InitFloor > {
  static const char* value()
  {
    return "ff7605597ae53414f57ec4bc282ae9d3";
  }

  static const char* value(const ::campusrover_msgs::InitFloor&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::InitFloor > {
  static const char* value()
  {
    return "campusrover_msgs/InitFloor";
  }

  static const char* value(const ::campusrover_msgs::InitFloor&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::InitFloorRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::InitFloor >
template<>
struct MD5Sum< ::campusrover_msgs::InitFloorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::InitFloor >::value();
  }
  static const char* value(const ::campusrover_msgs::InitFloorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::InitFloorRequest> should match
// service_traits::DataType< ::campusrover_msgs::InitFloor >
template<>
struct DataType< ::campusrover_msgs::InitFloorRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::InitFloor >::value();
  }
  static const char* value(const ::campusrover_msgs::InitFloorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::InitFloorResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::InitFloor >
template<>
struct MD5Sum< ::campusrover_msgs::InitFloorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::InitFloor >::value();
  }
  static const char* value(const ::campusrover_msgs::InitFloorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::InitFloorResponse> should match
// service_traits::DataType< ::campusrover_msgs::InitFloor >
template<>
struct DataType< ::campusrover_msgs::InitFloorResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::InitFloor >::value();
  }
  static const char* value(const ::campusrover_msgs::InitFloorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_INITFLOOR_H
