// Generated by gencpp from file campusrover_msgs/LocalizerSwitchRequest.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_LOCALIZERSWITCHREQUEST_H
#define CAMPUSROVER_MSGS_MESSAGE_LOCALIZERSWITCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct LocalizerSwitchRequest_
{
  typedef LocalizerSwitchRequest_<ContainerAllocator> Type;

  LocalizerSwitchRequest_()
    : mode(0)
    , building()
    , floor()
    , init_point()  {
    }
  LocalizerSwitchRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , building(_alloc)
    , floor(_alloc)
    , init_point(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _building_type;
  _building_type building;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _floor_type;
  _floor_type floor;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _init_point_type;
  _init_point_type init_point;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_DISABLE)
  #undef MODE_DISABLE
#endif
#if defined(_WIN32) && defined(MODE_ENABLE)
  #undef MODE_ENABLE
#endif
#if defined(_WIN32) && defined(MODE_PURE_2D_SCANMATCHING)
  #undef MODE_PURE_2D_SCANMATCHING
#endif

  enum {
    MODE_DISABLE = 0u,
    MODE_ENABLE = 1u,
    MODE_PURE_2D_SCANMATCHING = 2u,
  };


  typedef boost::shared_ptr< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizerSwitchRequest_

typedef ::campusrover_msgs::LocalizerSwitchRequest_<std::allocator<void> > LocalizerSwitchRequest;

typedef boost::shared_ptr< ::campusrover_msgs::LocalizerSwitchRequest > LocalizerSwitchRequestPtr;
typedef boost::shared_ptr< ::campusrover_msgs::LocalizerSwitchRequest const> LocalizerSwitchRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.building == rhs.building &&
    lhs.floor == rhs.floor &&
    lhs.init_point == rhs.init_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "154a6d53fbe1a8a8cdde5430bf063e54";
  }

  static const char* value(const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x154a6d53fbe1a8a8ULL;
  static const uint64_t static_value2 = 0xcdde5430bf063e54ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/LocalizerSwitchRequest";
  }

  static const char* value(const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 MODE_DISABLE = 0\n"
"uint8 MODE_ENABLE = 1\n"
"uint8 MODE_PURE_2D_SCANMATCHING = 2\n"
"\n"
"uint8 mode\n"
"string building\n"
"string floor\n"
"string init_point\n"
;
  }

  static const char* value(const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.building);
      stream.next(m.floor);
      stream.next(m.init_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizerSwitchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::LocalizerSwitchRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "building: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.building);
    s << indent << "floor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.floor);
    s << indent << "init_point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.init_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_LOCALIZERSWITCHREQUEST_H
