// Generated by gencpp from file campusrover_msgs/LocalizerLauncherResponse.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_LOCALIZERLAUNCHERRESPONSE_H
#define CAMPUSROVER_MSGS_MESSAGE_LOCALIZERLAUNCHERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct LocalizerLauncherResponse_
{
  typedef LocalizerLauncherResponse_<ContainerAllocator> Type;

  LocalizerLauncherResponse_()
    : pid(0)  {
    }
  LocalizerLauncherResponse_(const ContainerAllocator& _alloc)
    : pid(0)  {
  (void)_alloc;
    }



   typedef int16_t _pid_type;
  _pid_type pid;





  typedef boost::shared_ptr< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizerLauncherResponse_

typedef ::campusrover_msgs::LocalizerLauncherResponse_<std::allocator<void> > LocalizerLauncherResponse;

typedef boost::shared_ptr< ::campusrover_msgs::LocalizerLauncherResponse > LocalizerLauncherResponsePtr;
typedef boost::shared_ptr< ::campusrover_msgs::LocalizerLauncherResponse const> LocalizerLauncherResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator1> & lhs, const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pid == rhs.pid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator1> & lhs, const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1137d2b538a08de7b3b2fc45ff071459";
  }

  static const char* value(const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1137d2b538a08de7ULL;
  static const uint64_t static_value2 = 0xb3b2fc45ff071459ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/LocalizerLauncherResponse";
  }

  static const char* value(const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 pid\n"
;
  }

  static const char* value(const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizerLauncherResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::LocalizerLauncherResponse_<ContainerAllocator>& v)
  {
    s << indent << "pid: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_LOCALIZERLAUNCHERRESPONSE_H
