// Generated by gencpp from file campusrover_msgs/LocalizerSwitch.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_LOCALIZERSWITCH_H
#define CAMPUSROVER_MSGS_MESSAGE_LOCALIZERSWITCH_H

#include <ros/service_traits.h>


#include <campusrover_msgs/LocalizerSwitchRequest.h>
#include <campusrover_msgs/LocalizerSwitchResponse.h>


namespace campusrover_msgs
{

struct LocalizerSwitch
{

typedef LocalizerSwitchRequest Request;
typedef LocalizerSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalizerSwitch
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::LocalizerSwitch > {
  static const char* value()
  {
    return "a4fafa508ea4bd2a92362c5cfceeb827";
  }

  static const char* value(const ::campusrover_msgs::LocalizerSwitch&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::LocalizerSwitch > {
  static const char* value()
  {
    return "campusrover_msgs/LocalizerSwitch";
  }

  static const char* value(const ::campusrover_msgs::LocalizerSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::LocalizerSwitchRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::LocalizerSwitch >
template<>
struct MD5Sum< ::campusrover_msgs::LocalizerSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::LocalizerSwitch >::value();
  }
  static const char* value(const ::campusrover_msgs::LocalizerSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::LocalizerSwitchRequest> should match
// service_traits::DataType< ::campusrover_msgs::LocalizerSwitch >
template<>
struct DataType< ::campusrover_msgs::LocalizerSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::LocalizerSwitch >::value();
  }
  static const char* value(const ::campusrover_msgs::LocalizerSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::LocalizerSwitchResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::LocalizerSwitch >
template<>
struct MD5Sum< ::campusrover_msgs::LocalizerSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::LocalizerSwitch >::value();
  }
  static const char* value(const ::campusrover_msgs::LocalizerSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::LocalizerSwitchResponse> should match
// service_traits::DataType< ::campusrover_msgs::LocalizerSwitch >
template<>
struct DataType< ::campusrover_msgs::LocalizerSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::LocalizerSwitch >::value();
  }
  static const char* value(const ::campusrover_msgs::LocalizerSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_LOCALIZERSWITCH_H
