// Generated by gencpp from file campusrover_msgs/MapClosestLocation.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MAPCLOSESTLOCATION_H
#define CAMPUSROVER_MSGS_MESSAGE_MAPCLOSESTLOCATION_H

#include <ros/service_traits.h>


#include <campusrover_msgs/MapClosestLocationRequest.h>
#include <campusrover_msgs/MapClosestLocationResponse.h>


namespace campusrover_msgs
{

struct MapClosestLocation
{

typedef MapClosestLocationRequest Request;
typedef MapClosestLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapClosestLocation
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::MapClosestLocation > {
  static const char* value()
  {
    return "958ccb3e3caf31c023d2c553e7c87d27";
  }

  static const char* value(const ::campusrover_msgs::MapClosestLocation&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::MapClosestLocation > {
  static const char* value()
  {
    return "campusrover_msgs/MapClosestLocation";
  }

  static const char* value(const ::campusrover_msgs::MapClosestLocation&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::MapClosestLocationRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::MapClosestLocation >
template<>
struct MD5Sum< ::campusrover_msgs::MapClosestLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::MapClosestLocation >::value();
  }
  static const char* value(const ::campusrover_msgs::MapClosestLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::MapClosestLocationRequest> should match
// service_traits::DataType< ::campusrover_msgs::MapClosestLocation >
template<>
struct DataType< ::campusrover_msgs::MapClosestLocationRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::MapClosestLocation >::value();
  }
  static const char* value(const ::campusrover_msgs::MapClosestLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::MapClosestLocationResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::MapClosestLocation >
template<>
struct MD5Sum< ::campusrover_msgs::MapClosestLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::MapClosestLocation >::value();
  }
  static const char* value(const ::campusrover_msgs::MapClosestLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::MapClosestLocationResponse> should match
// service_traits::DataType< ::campusrover_msgs::MapClosestLocation >
template<>
struct DataType< ::campusrover_msgs::MapClosestLocationResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::MapClosestLocation >::value();
  }
  static const char* value(const ::campusrover_msgs::MapClosestLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MAPCLOSESTLOCATION_H
