// Generated by gencpp from file campusrover_msgs/MapInfoResponse.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MAPINFORESPONSE_H
#define CAMPUSROVER_MSGS_MESSAGE_MAPINFORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct MapInfoResponse_
{
  typedef MapInfoResponse_<ContainerAllocator> Type;

  MapInfoResponse_()
    : code()
    , message()  {
    }
  MapInfoResponse_(const ContainerAllocator& _alloc)
    : code(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _code_type;
  _code_type code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MapInfoResponse_

typedef ::campusrover_msgs::MapInfoResponse_<std::allocator<void> > MapInfoResponse;

typedef boost::shared_ptr< ::campusrover_msgs::MapInfoResponse > MapInfoResponsePtr;
typedef boost::shared_ptr< ::campusrover_msgs::MapInfoResponse const> MapInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "734fad93dcf1515c9778b32dbfa50cfc";
  }

  static const char* value(const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x734fad93dcf1515cULL;
  static const uint64_t static_value2 = 0x9778b32dbfa50cfcULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/MapInfoResponse";
  }

  static const char* value(const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string code\n"
"string message\n"
;
  }

  static const char* value(const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::MapInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::MapInfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.code);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MAPINFORESPONSE_H
