// Generated by gencpp from file campusrover_msgs/MapInitPoseRequest.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MAPINITPOSEREQUEST_H
#define CAMPUSROVER_MSGS_MESSAGE_MAPINITPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct MapInitPoseRequest_
{
  typedef MapInitPoseRequest_<ContainerAllocator> Type;

  MapInitPoseRequest_()
    : building()
    , floor()
    , init_point()  {
    }
  MapInitPoseRequest_(const ContainerAllocator& _alloc)
    : building(_alloc)
    , floor(_alloc)
    , init_point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _building_type;
  _building_type building;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _floor_type;
  _floor_type floor;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _init_point_type;
  _init_point_type init_point;





  typedef boost::shared_ptr< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapInitPoseRequest_

typedef ::campusrover_msgs::MapInitPoseRequest_<std::allocator<void> > MapInitPoseRequest;

typedef boost::shared_ptr< ::campusrover_msgs::MapInitPoseRequest > MapInitPoseRequestPtr;
typedef boost::shared_ptr< ::campusrover_msgs::MapInitPoseRequest const> MapInitPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.building == rhs.building &&
    lhs.floor == rhs.floor &&
    lhs.init_point == rhs.init_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0fbe64a4a5efcd8c5df81f9c6d224fb";
  }

  static const char* value(const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0fbe64a4a5efcd8ULL;
  static const uint64_t static_value2 = 0xc5df81f9c6d224fbULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/MapInitPoseRequest";
  }

  static const char* value(const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string building\n"
"string floor\n"
"string init_point\n"
;
  }

  static const char* value(const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.building);
      stream.next(m.floor);
      stream.next(m.init_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapInitPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::MapInitPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "building: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.building);
    s << indent << "floor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.floor);
    s << indent << "init_point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.init_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MAPINITPOSEREQUEST_H
