// Generated by gencpp from file campusrover_msgs/MapInfo.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MAPINFO_H
#define CAMPUSROVER_MSGS_MESSAGE_MAPINFO_H

#include <ros/service_traits.h>


#include <campusrover_msgs/MapInfoRequest.h>
#include <campusrover_msgs/MapInfoResponse.h>


namespace campusrover_msgs
{

struct MapInfo
{

typedef MapInfoRequest Request;
typedef MapInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapInfo
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::MapInfo > {
  static const char* value()
  {
    return "741eabcb755f63b90a295f90af3c64c8";
  }

  static const char* value(const ::campusrover_msgs::MapInfo&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::MapInfo > {
  static const char* value()
  {
    return "campusrover_msgs/MapInfo";
  }

  static const char* value(const ::campusrover_msgs::MapInfo&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::MapInfoRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::MapInfo >
template<>
struct MD5Sum< ::campusrover_msgs::MapInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::MapInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::MapInfoRequest> should match
// service_traits::DataType< ::campusrover_msgs::MapInfo >
template<>
struct DataType< ::campusrover_msgs::MapInfoRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::MapInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::MapInfoResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::MapInfo >
template<>
struct MD5Sum< ::campusrover_msgs::MapInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::MapInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::MapInfoResponse> should match
// service_traits::DataType< ::campusrover_msgs::MapInfo >
template<>
struct DataType< ::campusrover_msgs::MapInfoResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::MapInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MAPINFO_H
