// Generated by gencpp from file campusrover_msgs/MapLoadInfoRequest.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MAPLOADINFOREQUEST_H
#define CAMPUSROVER_MSGS_MESSAGE_MAPLOADINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct MapLoadInfoRequest_
{
  typedef MapLoadInfoRequest_<ContainerAllocator> Type;

  MapLoadInfoRequest_()
    : building()
    , floor()  {
    }
  MapLoadInfoRequest_(const ContainerAllocator& _alloc)
    : building(_alloc)
    , floor(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _building_type;
  _building_type building;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _floor_type;
  _floor_type floor;





  typedef boost::shared_ptr< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapLoadInfoRequest_

typedef ::campusrover_msgs::MapLoadInfoRequest_<std::allocator<void> > MapLoadInfoRequest;

typedef boost::shared_ptr< ::campusrover_msgs::MapLoadInfoRequest > MapLoadInfoRequestPtr;
typedef boost::shared_ptr< ::campusrover_msgs::MapLoadInfoRequest const> MapLoadInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.building == rhs.building &&
    lhs.floor == rhs.floor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b15058aba057dc225e6ed360700b819";
  }

  static const char* value(const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b15058aba057dc2ULL;
  static const uint64_t static_value2 = 0x25e6ed360700b819ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/MapLoadInfoRequest";
  }

  static const char* value(const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string building\n"
"string floor\n"
;
  }

  static const char* value(const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.building);
      stream.next(m.floor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapLoadInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::MapLoadInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "building: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.building);
    s << indent << "floor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.floor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MAPLOADINFOREQUEST_H
