// Generated by gencpp from file campusrover_msgs/MapLoadInfo.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MAPLOADINFO_H
#define CAMPUSROVER_MSGS_MESSAGE_MAPLOADINFO_H

#include <ros/service_traits.h>


#include <campusrover_msgs/MapLoadInfoRequest.h>
#include <campusrover_msgs/MapLoadInfoResponse.h>


namespace campusrover_msgs
{

struct MapLoadInfo
{

typedef MapLoadInfoRequest Request;
typedef MapLoadInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapLoadInfo
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::MapLoadInfo > {
  static const char* value()
  {
    return "93a21f63b64b29785779efda16301551";
  }

  static const char* value(const ::campusrover_msgs::MapLoadInfo&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::MapLoadInfo > {
  static const char* value()
  {
    return "campusrover_msgs/MapLoadInfo";
  }

  static const char* value(const ::campusrover_msgs::MapLoadInfo&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::MapLoadInfoRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::MapLoadInfo >
template<>
struct MD5Sum< ::campusrover_msgs::MapLoadInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::MapLoadInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapLoadInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::MapLoadInfoRequest> should match
// service_traits::DataType< ::campusrover_msgs::MapLoadInfo >
template<>
struct DataType< ::campusrover_msgs::MapLoadInfoRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::MapLoadInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapLoadInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::MapLoadInfoResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::MapLoadInfo >
template<>
struct MD5Sum< ::campusrover_msgs::MapLoadInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::MapLoadInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapLoadInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::MapLoadInfoResponse> should match
// service_traits::DataType< ::campusrover_msgs::MapLoadInfo >
template<>
struct DataType< ::campusrover_msgs::MapLoadInfoResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::MapLoadInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::MapLoadInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MAPLOADINFO_H
