// Generated by gencpp from file campusrover_msgs/ModuleInfo.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MODULEINFO_H
#define CAMPUSROVER_MSGS_MESSAGE_MODULEINFO_H

#include <ros/service_traits.h>


#include <campusrover_msgs/ModuleInfoRequest.h>
#include <campusrover_msgs/ModuleInfoResponse.h>


namespace campusrover_msgs
{

struct ModuleInfo
{

typedef ModuleInfoRequest Request;
typedef ModuleInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModuleInfo
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::ModuleInfo > {
  static const char* value()
  {
    return "55d2c427bdf7bbce8ecb662848fd46e6";
  }

  static const char* value(const ::campusrover_msgs::ModuleInfo&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::ModuleInfo > {
  static const char* value()
  {
    return "campusrover_msgs/ModuleInfo";
  }

  static const char* value(const ::campusrover_msgs::ModuleInfo&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::ModuleInfoRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::ModuleInfo >
template<>
struct MD5Sum< ::campusrover_msgs::ModuleInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ModuleInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::ModuleInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ModuleInfoRequest> should match
// service_traits::DataType< ::campusrover_msgs::ModuleInfo >
template<>
struct DataType< ::campusrover_msgs::ModuleInfoRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ModuleInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::ModuleInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::ModuleInfoResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::ModuleInfo >
template<>
struct MD5Sum< ::campusrover_msgs::ModuleInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::ModuleInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::ModuleInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::ModuleInfoResponse> should match
// service_traits::DataType< ::campusrover_msgs::ModuleInfo >
template<>
struct DataType< ::campusrover_msgs::ModuleInfoResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::ModuleInfo >::value();
  }
  static const char* value(const ::campusrover_msgs::ModuleInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MODULEINFO_H
