// Generated by gencpp from file campusrover_msgs/MPCParameter.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_MPCPARAMETER_H
#define CAMPUSROVER_MSGS_MESSAGE_MPCPARAMETER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace campusrover_msgs
{
template <class ContainerAllocator>
struct MPCParameter_
{
  typedef MPCParameter_<ContainerAllocator> Type;

  MPCParameter_()
    : header()
    , child_frame_id()
    , position_x(0.0)
    , position_y(0.0)
    , position_theta(0.0)
    , linear_x(0.0)
    , angular_z(0.0)  {
    }
  MPCParameter_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , child_frame_id(_alloc)
    , position_x(0.0)
    , position_y(0.0)
    , position_theta(0.0)
    , linear_x(0.0)
    , angular_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _child_frame_id_type;
  _child_frame_id_type child_frame_id;

   typedef double _position_x_type;
  _position_x_type position_x;

   typedef double _position_y_type;
  _position_y_type position_y;

   typedef double _position_theta_type;
  _position_theta_type position_theta;

   typedef double _linear_x_type;
  _linear_x_type linear_x;

   typedef double _angular_z_type;
  _angular_z_type angular_z;





  typedef boost::shared_ptr< ::campusrover_msgs::MPCParameter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::MPCParameter_<ContainerAllocator> const> ConstPtr;

}; // struct MPCParameter_

typedef ::campusrover_msgs::MPCParameter_<std::allocator<void> > MPCParameter;

typedef boost::shared_ptr< ::campusrover_msgs::MPCParameter > MPCParameterPtr;
typedef boost::shared_ptr< ::campusrover_msgs::MPCParameter const> MPCParameterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::MPCParameter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::MPCParameter_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MPCParameter_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.child_frame_id == rhs.child_frame_id &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_theta == rhs.position_theta &&
    lhs.linear_x == rhs.linear_x &&
    lhs.angular_z == rhs.angular_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::MPCParameter_<ContainerAllocator1> & lhs, const ::campusrover_msgs::MPCParameter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::MPCParameter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::MPCParameter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::MPCParameter_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7042ea7c7a5210398b974d0e1f9047b2";
  }

  static const char* value(const ::campusrover_msgs::MPCParameter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7042ea7c7a521039ULL;
  static const uint64_t static_value2 = 0x8b974d0e1f9047b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/MPCParameter";
  }

  static const char* value(const ::campusrover_msgs::MPCParameter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string child_frame_id\n"
"float64 position_x\n"
"float64 position_y\n"
"float64 position_theta\n"
"float64 linear_x\n"
"float64 angular_z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::campusrover_msgs::MPCParameter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.child_frame_id);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_theta);
      stream.next(m.linear_x);
      stream.next(m.angular_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MPCParameter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::MPCParameter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::MPCParameter_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "child_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.child_frame_id);
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_theta: ";
    Printer<double>::stream(s, indent + "  ", v.position_theta);
    s << indent << "linear_x: ";
    Printer<double>::stream(s, indent + "  ", v.linear_x);
    s << indent << "angular_z: ";
    Printer<double>::stream(s, indent + "  ", v.angular_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_MPCPARAMETER_H
