// Generated by gencpp from file campusrover_msgs/NodeInfo.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_NODEINFO_H
#define CAMPUSROVER_MSGS_MESSAGE_NODEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace campusrover_msgs
{
template <class ContainerAllocator>
struct NodeInfo_
{
  typedef NodeInfo_<ContainerAllocator> Type;

  NodeInfo_()
    : name()
    , pose()  {
    }
  NodeInfo_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::campusrover_msgs::NodeInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::NodeInfo_<ContainerAllocator> const> ConstPtr;

}; // struct NodeInfo_

typedef ::campusrover_msgs::NodeInfo_<std::allocator<void> > NodeInfo;

typedef boost::shared_ptr< ::campusrover_msgs::NodeInfo > NodeInfoPtr;
typedef boost::shared_ptr< ::campusrover_msgs::NodeInfo const> NodeInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::NodeInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::NodeInfo_<ContainerAllocator1> & lhs, const ::campusrover_msgs::NodeInfo_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::NodeInfo_<ContainerAllocator1> & lhs, const ::campusrover_msgs::NodeInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::NodeInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::NodeInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::NodeInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "177d54286ddeee12eba514054bddffd5";
  }

  static const char* value(const ::campusrover_msgs::NodeInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x177d54286ddeee12ULL;
  static const uint64_t static_value2 = 0xeba514054bddffd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/NodeInfo";
  }

  static const char* value(const ::campusrover_msgs::NodeInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::campusrover_msgs::NodeInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::NodeInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::NodeInfo_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_NODEINFO_H
