// Generated by gencpp from file campusrover_msgs/RLObservationArray.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_RLOBSERVATIONARRAY_H
#define CAMPUSROVER_MSGS_MESSAGE_RLOBSERVATIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <campusrover_msgs/RLObservation.h>

namespace campusrover_msgs
{
template <class ContainerAllocator>
struct RLObservationArray_
{
  typedef RLObservationArray_<ContainerAllocator> Type;

  RLObservationArray_()
    : header()
    , observation()  {
    }
  RLObservationArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , observation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::campusrover_msgs::RLObservation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::campusrover_msgs::RLObservation_<ContainerAllocator> >> _observation_type;
  _observation_type observation;





  typedef boost::shared_ptr< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> const> ConstPtr;

}; // struct RLObservationArray_

typedef ::campusrover_msgs::RLObservationArray_<std::allocator<void> > RLObservationArray;

typedef boost::shared_ptr< ::campusrover_msgs::RLObservationArray > RLObservationArrayPtr;
typedef boost::shared_ptr< ::campusrover_msgs::RLObservationArray const> RLObservationArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::RLObservationArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::RLObservationArray_<ContainerAllocator1> & lhs, const ::campusrover_msgs::RLObservationArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.observation == rhs.observation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::RLObservationArray_<ContainerAllocator1> & lhs, const ::campusrover_msgs::RLObservationArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b9bc5aef578d2bb524b67bcebb72c92";
  }

  static const char* value(const ::campusrover_msgs::RLObservationArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b9bc5aef578d2bbULL;
  static const uint64_t static_value2 = 0x524b67bcebb72c92ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/RLObservationArray";
  }

  static const char* value(const ::campusrover_msgs::RLObservationArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"campusrover_msgs/RLObservation[] observation\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: campusrover_msgs/RLObservation\n"
"std_msgs/Header header\n"
"float32[] observation_value\n"
;
  }

  static const char* value(const ::campusrover_msgs::RLObservationArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.observation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLObservationArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::RLObservationArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::RLObservationArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "observation[]" << std::endl;
    for (size_t i = 0; i < v.observation.size(); ++i)
    {
      s << indent << "  observation[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::campusrover_msgs::RLObservation_<ContainerAllocator> >::stream(s, indent + "    ", v.observation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_RLOBSERVATIONARRAY_H
