// Generated by gencpp from file campusrover_msgs/RLObservation.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_RLOBSERVATION_H
#define CAMPUSROVER_MSGS_MESSAGE_RLOBSERVATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace campusrover_msgs
{
template <class ContainerAllocator>
struct RLObservation_
{
  typedef RLObservation_<ContainerAllocator> Type;

  RLObservation_()
    : header()
    , observation_value()  {
    }
  RLObservation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , observation_value(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _observation_value_type;
  _observation_value_type observation_value;





  typedef boost::shared_ptr< ::campusrover_msgs::RLObservation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::RLObservation_<ContainerAllocator> const> ConstPtr;

}; // struct RLObservation_

typedef ::campusrover_msgs::RLObservation_<std::allocator<void> > RLObservation;

typedef boost::shared_ptr< ::campusrover_msgs::RLObservation > RLObservationPtr;
typedef boost::shared_ptr< ::campusrover_msgs::RLObservation const> RLObservationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::RLObservation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::RLObservation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::RLObservation_<ContainerAllocator1> & lhs, const ::campusrover_msgs::RLObservation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.observation_value == rhs.observation_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::RLObservation_<ContainerAllocator1> & lhs, const ::campusrover_msgs::RLObservation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::RLObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::RLObservation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::RLObservation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "584d45121da53af3af59190cf228b410";
  }

  static const char* value(const ::campusrover_msgs::RLObservation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x584d45121da53af3ULL;
  static const uint64_t static_value2 = 0xaf59190cf228b410ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/RLObservation";
  }

  static const char* value(const ::campusrover_msgs::RLObservation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32[] observation_value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::campusrover_msgs::RLObservation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.observation_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLObservation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::RLObservation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::RLObservation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "observation_value[]" << std::endl;
    for (size_t i = 0; i < v.observation_value.size(); ++i)
    {
      s << indent << "  observation_value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.observation_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_RLOBSERVATION_H
