// Generated by gencpp from file campusrover_msgs/RoutingPathRequest.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_ROUTINGPATHREQUEST_H
#define CAMPUSROVER_MSGS_MESSAGE_ROUTINGPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct RoutingPathRequest_
{
  typedef RoutingPathRequest_<ContainerAllocator> Type;

  RoutingPathRequest_()
    : origin()
    , destination()  {
    }
  RoutingPathRequest_(const ContainerAllocator& _alloc)
    : origin(_alloc)
    , destination(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _origin_type;
  _origin_type origin;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RoutingPathRequest_

typedef ::campusrover_msgs::RoutingPathRequest_<std::allocator<void> > RoutingPathRequest;

typedef boost::shared_ptr< ::campusrover_msgs::RoutingPathRequest > RoutingPathRequestPtr;
typedef boost::shared_ptr< ::campusrover_msgs::RoutingPathRequest const> RoutingPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.origin == rhs.origin &&
    lhs.destination == rhs.destination;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77229e9944c3c5be734d31593688977f";
  }

  static const char* value(const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77229e9944c3c5beULL;
  static const uint64_t static_value2 = 0x734d31593688977fULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/RoutingPathRequest";
  }

  static const char* value(const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string origin\n"
"string[] destination\n"
;
  }

  static const char* value(const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.origin);
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoutingPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::RoutingPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "origin: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.origin);
    s << indent << "destination[]" << std::endl;
    for (size_t i = 0; i < v.destination.size(); ++i)
    {
      s << indent << "  destination[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destination[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_ROUTINGPATHREQUEST_H
