// Generated by gencpp from file campusrover_msgs/TargetButtonRequest.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_TARGETBUTTONREQUEST_H
#define CAMPUSROVER_MSGS_MESSAGE_TARGETBUTTONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campusrover_msgs
{
template <class ContainerAllocator>
struct TargetButtonRequest_
{
  typedef TargetButtonRequest_<ContainerAllocator> Type;

  TargetButtonRequest_()
    : target_button()  {
    }
  TargetButtonRequest_(const ContainerAllocator& _alloc)
    : target_button(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_button_type;
  _target_button_type target_button;





  typedef boost::shared_ptr< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TargetButtonRequest_

typedef ::campusrover_msgs::TargetButtonRequest_<std::allocator<void> > TargetButtonRequest;

typedef boost::shared_ptr< ::campusrover_msgs::TargetButtonRequest > TargetButtonRequestPtr;
typedef boost::shared_ptr< ::campusrover_msgs::TargetButtonRequest const> TargetButtonRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_button == rhs.target_button;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator1> & lhs, const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace campusrover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "013dc2c493459992317504da01e1af73";
  }

  static const char* value(const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x013dc2c493459992ULL;
  static const uint64_t static_value2 = 0x317504da01e1af73ULL;
};

template<class ContainerAllocator>
struct DataType< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campusrover_msgs/TargetButtonRequest";
  }

  static const char* value(const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string target_button\n"
;
  }

  static const char* value(const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetButtonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campusrover_msgs::TargetButtonRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_button: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_button);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_TARGETBUTTONREQUEST_H
