// Generated by gencpp from file campusrover_msgs/VSParameter.msg
// DO NOT EDIT!


#ifndef CAMPUSROVER_MSGS_MESSAGE_VSPARAMETER_H
#define CAMPUSROVER_MSGS_MESSAGE_VSPARAMETER_H

#include <ros/service_traits.h>


#include <campusrover_msgs/VSParameterRequest.h>
#include <campusrover_msgs/VSParameterResponse.h>


namespace campusrover_msgs
{

struct VSParameter
{

typedef VSParameterRequest Request;
typedef VSParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VSParameter
} // namespace campusrover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::campusrover_msgs::VSParameter > {
  static const char* value()
  {
    return "131799e53a81bae950535949b6dfa532";
  }

  static const char* value(const ::campusrover_msgs::VSParameter&) { return value(); }
};

template<>
struct DataType< ::campusrover_msgs::VSParameter > {
  static const char* value()
  {
    return "campusrover_msgs/VSParameter";
  }

  static const char* value(const ::campusrover_msgs::VSParameter&) { return value(); }
};


// service_traits::MD5Sum< ::campusrover_msgs::VSParameterRequest> should match
// service_traits::MD5Sum< ::campusrover_msgs::VSParameter >
template<>
struct MD5Sum< ::campusrover_msgs::VSParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::VSParameter >::value();
  }
  static const char* value(const ::campusrover_msgs::VSParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::VSParameterRequest> should match
// service_traits::DataType< ::campusrover_msgs::VSParameter >
template<>
struct DataType< ::campusrover_msgs::VSParameterRequest>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::VSParameter >::value();
  }
  static const char* value(const ::campusrover_msgs::VSParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::campusrover_msgs::VSParameterResponse> should match
// service_traits::MD5Sum< ::campusrover_msgs::VSParameter >
template<>
struct MD5Sum< ::campusrover_msgs::VSParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::campusrover_msgs::VSParameter >::value();
  }
  static const char* value(const ::campusrover_msgs::VSParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::campusrover_msgs::VSParameterResponse> should match
// service_traits::DataType< ::campusrover_msgs::VSParameter >
template<>
struct DataType< ::campusrover_msgs::VSParameterResponse>
{
  static const char* value()
  {
    return DataType< ::campusrover_msgs::VSParameter >::value();
  }
  static const char* value(const ::campusrover_msgs::VSParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMPUSROVER_MSGS_MESSAGE_VSPARAMETER_H
